### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Stebulous** [Kinlei/MaterialLua#12]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be an in-built toggle ui option for fully hiding the ui.

**Describe the solution you'd like**
A keybind option, and a toggle function for it.

**Describe alternatives you've considered**
I've considered leaving a functionless button to act as a label to just tell the user they keybind i would hard code into the script

**Additional context**
A rebindable keybind such as in [Venyx UI Lib](https://github.com/GreenDeno/Venyx-UI-Library) would be amazing.

**Comment by Kinlei** [comment]
You could create a scuffed keybind using a TextField and your own keybind function. MaterialLua is discontinued.
