### ISSUE TITLE
Pop up selection UI

### ISSUE THREAD

**Issue by Xowie89** [Kinlei/MaterialLua#13]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A new function to create a temporary UI popup like the main UI but with its own UI elements.

**Describe alternatives you've considered**
Constructing my own but the design is all wrong and ugly.

**Additional context**
The thing I am working on entails selecting a storage container having a UI pop up with all the resources you can put in that container and upon selecting one the UI goes away.

**Comment by Kinlei** [comment]
So you want an extra framework?
