### ISSUE TITLE
Dropdown pre-selection

### ISSUE THREAD

**Issue by Xowie89** [Kinlei/MaterialLua#14]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A way to define a pre-selected dropdown menu item.

**Describe alternatives you've considered**
I cant seem to figure out anyway to do this as I cant figure out how to manipulate the UI to do what I want it to do.

**Additional context**
Pre-pick and display one of the options in the dropdown list.

**Comment by Stefanuk12** [comment]
I added this within my [fork](https://github.com/Stefanuk12/MaterialLua)
