### ISSUE TITLE
Having problems with toggles

### ISSUE THREAD

**Issue by technorav3nn** [Kinlei/MaterialLua#9]
So i usually used wally v3 ui lib, and toggles were fine, but how do I return the state of toggle?

Basically I just want it so that if its switched on it will return true and run the true script, and if its off it will return false and return the false script.

Kinda confused whilst reading the documentation, thanks

**Comment by Kinlei** [comment]
Hi. Usually you have a variable outside of the toggle and a while loop checking for the condition of the toggle. 

For example:

```
local var = false;

local B = Y.Toggle({
	Text = "I'm a switch",
	Callback = function(Value)
		var = Value
	end,
	Enabled = var
});

while true do
    if var then
        print("var enabled:", var);
    end
    wait();
end;
```
